version: "3.7"

services:
    backend:
        build:
            args:
                user: lucas
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: tavred-be
        ports:
            - 8000:8000
        container_name: tavred_app
        restart: unless-stopped
        working_dir: /var/www
        networks:
            - tavred

    db:
        image: mysql:8.0.33
        container_name: tavred-db
        restart: unless-stopped
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        networks:
            - tavred
volumes:
    db-data:
networks:
    tavred:
        driver: bridge
