version: "3.7"

services:
    db:
        image: mysql:8.0.33
        container_name: tavred-db
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: tavola
            MYSQL_ROOT_PASSWORD: none
            MYSQL_PASSWORD: none
            MYSQL_USER: lucas
